spring.application.name=FinanceTracker

#Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/FinanceTracker
#${DB_USERNAME}
spring.datasource.username=${DB_USERNAME}
#${DB_PASSWORD}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secretKey=odjsfnahpu9ewuhfijerh9eewr8eribto847t38fb847fgh384fyubw984gfw98rhfewurgdoifha9difpoadihf9